import { Type } from '@sinclair/typebox'

export const businessSchema = {
  create: Type.Object({
    name: Type.String(),
    email: Type.String(),
    phone: Type.String(),
    whatsappNumber: Type.Optional(Type.String()),
    address: Type.String(),
    industry: Type.Optional(Type.String()),
    bio: Type.Optional(Type.String()),
    logo: Type.String(),
    cover: Type.Optional(Type.String()),
    twitterLink: Type.Optional(Type.String()),
    facebookLink: Type.Optional(Type.String()),
    instagramLink: Type.Optional(Type.String()),
    linkedinLink: Type.Optional(Type.String()),
  }),
  update: Type.Object({
    name: Type.Optional(Type.String()),
    email: Type.Optional(Type.String()),
    phone: Type.Optional(Type.String()),
    whatsappNumber: Type.Optional(Type.String()),
    address: Type.Optional(Type.String()),
    industry: Type.Optional(Type.String()),
    bio: Type.Optional(Type.String()),
    logo: Type.Optional(Type.String()),
    cover: Type.Optional(Type.String()),
    twitterLink: Type.Optional(Type.String()),
    facebookLink: Type.Optional(Type.String()),
    instagramLink: Type.Optional(Type.String()),
    linkedinLink: Type.Optional(Type.String()),
  }),
  delete: Type.Object({ id: Type.Number() }),
  get: Type.Object({
    id: Type.Number(),
    name: Type.String(),
    email: Type.String(),
    phone: Type.String(),
    whatsappNumber: Type.Optional(Type.String()),
    address: Type.String(),
    industry: Type.Optional(Type.String()),
    bio: Type.Optional(Type.String()),
    logo: Type.String(),
    cover: Type.Optional(Type.String()),
    twitterLink: Type.Optional(Type.String()),
    facebookLink: Type.Optional(Type.String()),
    instagramLink: Type.Optional(Type.String()),
    linkedinLink: Type.Optional(Type.String()),

    createdAt: Type.String({ format: 'date-time' }),
    updatedAt: Type.String({ format: 'date-time' }),
  }),
}
