name: Deploy To EC2 Instance On Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/thrive
          remote_host: ec2-3-88-77-139.compute-1.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.NKJGVVHGJKN }}"
