on:
  push:
   branches:
     - master

name: Deploy on push

jobs:
  web-deploy:
    
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Use NodeJs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Project
        run: |
          npm install
          npm run build

      
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cybertechdigitals.com
          username: ${{secrets.ftp_username}}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
